FROM registry.suse.com/bci/bci-base:15.4

ARG ARCH=amd64
ENV ARCH=${ARCH}
RUN zypper rm -y container-suseconnect && \
    zypper ar --priority=200 http://download.opensuse.org/distribution/leap/15.4/repo/oss repo-oss && \
    zypper --no-gpg-checks ref && \
    zypper in -y curl nginx && zypper clean -a